### ISSUE TITLE
Android Firebase.core crash app 

### ISSUE THREAD

**Issue by kezai** [hansemannn/titanium-firebase#11]
Hello,

When I add firebase.core module to my project, the app on device crash directly and doesn't start.
I tried on different devices with different titanium SDK, I have the same issue.

What do you advise to me to do please ?
thanks in advance.

**Comment by R4mpancy** [comment]
I would advise you to re-submit this issue in the [titanium-firebase-core](https://github.com/hansemannn/titanium-firebase-core) repo and make sure to include which platform (iOS or Android) you're experiencing the crash, and versions for which titanium SDK and firebase modules that you're using.

**Comment by ulissesrsilva** [comment]
@kezai, check if you are using the last release. I installed via gittio, and it came with the 2.0.0 version, and the app was crashing just like you described. The latest release is the 5.0.0

**Comment by ulissesrsilva** [comment]
@kezai I had the same problem! Check this (resolved, 🙏) issue https://github.com/hansemannn/titanium-firebase-core/issues/47#issue-482912557
