### ISSUE TITLE
Link to Ti.Firestore project from README

### ISSUE THREAD

**Issue by de1mat** [hansemannn/titanium-firebase#16]
I have not played with this yet, but will be soon. It would be good to have this linked to from the README to make it easier to locate...

https://github.com/AppWerft/Ti.Firestore

**Comment by hansemannn** [comment]
The repository only includes Android and has "work in progress" everywhere. I would rather not want to link it in the well maintained modules listed here. If it's a prio to have Firestore working, let me know and I could maybe implement it in the fashion the other modules were created.

**Comment by de1mat** [comment]
Thanks @hansemannn . Understood. Yes to me it seems that Firestore is what is recommended by Google as the default goto for multiple reasons and would suit better for my requirements. If possible Firestore support would be amazing.
