### ISSUE TITLE
 Update Firebase iOS to v 8.X

### ISSUE THREAD

**Issue by Astrovic** [hansemannn/titanium-firebase#22]
Hi, I tried to update to the latest version of Firebase iOS 8.8 (https://github.com/Astrovic/titanium-firebase-core and https://github.com/Astrovic/titanium-firebase-analytics). 
I simply downloaded the SDK (as documented here https://github.com/hansemannn/titanium-firebase-analytics#update-sdks) and updated the framworks in the `/shared` and `/platform` folders. But on the Firebase console I don't see the logs.
Maybe it's not enough just to update the SDK?

**Comment by hansemannn** [comment]
Usually you always update at least core and analytics, so that was correct. Logs can take a bit of time, so maybe wait a few more hours. Let me know if it still persists early tomorrow. And please do a PR so I/we can help reviewing!

**Comment by Astrovic** [comment]
Yes, in fact I have updated the core and analytics, but it doesn't work. I have also updated in-app-messaging, but the messages are not arriving. With the previous versions, however, everything works correctly, and the log analytics arrive after a few minutes. Maybe there was some change from 7.x to 8.x.
I saw that in version 8.x there is no longer the `FirebaseInstanceID` framework. Maybe this is the problem?
Anyway I send the PRs in all the repositories so maybe you can check.

**Comment by Astrovic** [comment]
I did other tests, now the logs are working correctly. In-App Messaging and Cloud Messaging also work correctly. Perhaps it was a momentary problem with the Firebase console. Therefore all PR could be accepted:
https://github.com/hansemannn/titanium-firebase-core/pull/62
https://github.com/hansemannn/titanium-firebase-analytics/pull/67
https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/133
https://github.com/hansemannn/titanium-firebase-in-app-messaging/pull/1

**Comment by hansemannn** [comment]
Cleaning up :-)
