### ISSUE TITLE
Suggestion: List module versions in the readme

### ISSUE THREAD

**Issue by Arood** [hansemannn/titanium-firebase#26]
I often find myself having to go through my projects and each submodule to check if there are any updates to do. It would be nice time-saver if you could see the latest version of each module in the overview.

Perhaps the easiest way would be to include a badge in each repo that can be linked in the Features-table? It might even be possible to create automatically with some kind of badge generator?

**Comment by hansemannn** [comment]
If you find a badge that gets this info, I'd be happy to include it! Manually maintaining all versions is quite annoying :/

EDIT: May found something! https://shields.io/badges/git-hub-release-latest-by-sem-ver-including-pre-releases
EDIT2: We still need to specify the version manually there. And it's a bit more complex, as we maintain both iOS- and Android releases under /releases

**Comment by Arood** [comment]
It seems like https://shields.io/badges/dynamic-yaml-badge could work, if you create one per platform and link to the manifest file and query version?

**Comment by Arood** [comment]
For example: `https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fhansemannn%2Ftitanium-firebase-analytics%2Fmain%2Fios%2Fmanifest&query=version&label=iOS`

would create:

![](https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fhansemannn%2Ftitanium-firebase-analytics%2Fmain%2Fios%2Fmanifest&query=version&label=iOS)

**Comment by hansemannn** [comment]
Very nice!

**Comment by hansemannn** [comment]
Can you do a PR please to add them? Then we are ready here. That'd be a great contribution, even outside pure code contributions.

**Comment by Arood** [comment]
Sure, I could take a look
