### ISSUE TITLE
Uncaught translation error: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by qlzqlzqlz** [hansemannn/titanium-firebase#9]
Hi,
I've been trying to integrate Firebase/Push Notifications into my Titanium app and I am getting this issue while compilation with `firebase.core` module. Stack trace as follows:

[INFO] :   Running dexer: (ARGS)
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lfirebase/core/TitaniumFirebaseCoreBootstrap;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lfirebase/core/TitaniumFirebaseCoreModule;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lfirebase/core/TitaniumFirebaseCoreModule$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lfirebase/core/TitaniumFirebaseCoreModule$2;
[ERROR] :  4 errors; aborting
[ERROR] Application Installer abnormal process termination. Process exit value was 1

Any help regarding this would be much appreciated
Project Config : 
Titanium v7.5.0
Node v 11.6.0
firebase.core v3.2.0 (also tried with 3.0.0 and 2.3.0)
ti.playservices v11.0.40 (also tried with 11.8.0)
hyperloop v3.1.4
Appc v7.0.9

Thanks

**Comment by hansemannn** [comment]
It looks like you already included the Firebase Core library somewhere else (maybe from another module or Hyperloop).

**Comment by qlzqlzqlz** [comment]
It was indeed imported from another module, thank you.
Removing the other module fixed it.
